alias fm=". ranger"
alias db="termdbms"
alias bell="play -q ~/Audio/bell.ogg"
alias vm="sudo virt-manager"
alias yt="ytfzf -st"
alias ytdl=yt-dlp
alias screensaver=Scripts/animation.sh
alias calendar=calcurse
alias bitcoin="curl rate.sx"
alias cheat=Scripts/cheat.sh
alias clock="clear && tty-clock -C 1 -c -s"
alias gemini=amfora
alias gopher=phetch
alias map=mapscii
alias pdf=green
alias podcast=castero
alias reddit="tuir --enable-media -s neovim"
alias rss=newsboat
alias wiki="phetch gopher://gopherpedia.com:70"
alias www="w3m http://searx:8080"
alias sndvol=pulsemixer
alias weather=Scripts/weather.sh
alias disk=ncdu
alias lang-detect="~/Scripts/lang-detect.sh"
alias pixel-editor="aseprite"
alias jack-init=Scripts/jack-init.sh
alias torrent=transmission-cli
alias torrent-search="we-get --search"
alias download=aria2c
alias search=fd
alias fuzzy="fzf --preview='bat {}'"
alias browser=uzbl-tabbed
alias solitaire="ttysolitaire"
alias tetris="bastet"
alias net-manager=nmtui
alias net-monitor="sudo nethogs"
alias prev=prevd
alias next=nextd
alias telegram="nchat"
alias stumble="~/Scripts/stumble.sh"
alias revisit="~/Scripts/revisit.sh"
alias open="~/Scripts/link-handler.sh"
alias websearch="sr sx"
