#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "orbital"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    guifont = "mononoki Nerd Font Mono:h8"
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    statusline_left_sections = [
      'winnr',
      'major mode',
      'filename',
      'fileformat',
      'minor mode lighters',
      'version control info',
      'search status'
    ]

    statusline_right_sections = [
      'cursorpos',
      'percentage',
      'input method',
      'date',
      'time'
    ]

    buffer_index_type = 0
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"
    #filemanager = "nerdtree"
    relativenumber = false
    automatic_update = true

 custom_color_palette = [
         ["Yellow", "#111111", 246, 235],
         ["DarkGray", "Black", 239, 246],
         ["#a89984", "Black", 237, 246],
         ["#000000", 241],
         ["#ffffff", "Black", 235, 109],
         ["#282828", "Black", 235, 208],
         ["#282828", "Black", 235, 108],
         ["#282828", "Black", 235, 72],
         ["#282828", "Black", 235, 132],
     ]
 
[[layers]]
name = "colorscheme"
random_theme = false 

[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "cycle"
autocomplete_method = "coc"
snippet_engine = "ultisnips"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "lang#c"

[[layers]]
name = "lang#html"

# [[layers]]
# name = "lang#javascript"
 
# [[layers]]
# name = "core#tabline"

[[layers]]
name = "lang#markdown"

[[layers]]
name = "VersionControl"

[[layers]]
name = "fzf"

# [[custom_plugins]]
# name = 'victorze/foo' 

[[custom_plugins]]
name = 'rafi/awesome-vim-colorschemes'

[[custom_plugins]]
name = 'mcchrish/vim-no-color-collections'

[[custom_plugins]]
name = 'eliba2/vim-node-inspect'

[[custom_plugins]]
name = 'moll/vim-bbye'

[[custom_plugins]]
name = 'raimondi/delimitmate'

[[custom_plugins]]
name = 'maxbrunsfeld/vim-yankstack' 

[[custom_plugins]]
name = 'kshenoy/vim-signature' 

[[custom_plugins]]
name = 'neomake/neomake' 

[[custom_plugins]]
name = 'voldikss/vim-floaterm' 

[[custom_plugins]]
name = 'kyazdani42/nvim-web-devicons' 

[[custom_plugins]]
name = 'romgrk/barbar.nvim' 

[[custom_plugins]]
name = 'junegunn/fzf.vim'

[[custom_plugins]]
name = 'jesseleite/vim-agriculture'

[[custom_plugins]]
name = 'junegunn/limelight.vim'

[[custom_plugins]]
name = 'hushicai/tagbar-javascript.vim'

[[custom_plugins]]
name = 'ludovicchabant/vim-gutentags'
