#!/bin/bash

alias browser=qutebrowser
alias bell="play -q ~/Audio/bell.ogg"
alias bitcoin="coinmon"
alias calendar=calcurse
alias cheat=Scripts/cheat.sh
alias clock="clear && tty-clock -C 1 -c -s"
alias disk=ncdu
alias disk-usage=duf
alias db="termdbms"
alias download=aria2c
alias ebook="epy"
alias fm=". ranger"
alias fuzzy="fzf --preview='bat {}'"
alias gemini=amfora
alias gopher=phetch
alias jack-init=Scripts/jack-init.sh
alias lang-detect="/home/unknown/Development/sandbox/lang-detect/lang-detect.sh"
alias map=mapscii
alias net-manager=nmtui
alias net-monitor="sudo nethogs"
alias next=nextd
alias open="~/Scripts/link-handler.sh"
alias pdf=green
alias pixel-editor="/home/unknown/.local/share/Steam/steamapps/common/Aseprite/aseprite"
alias podcast=castero
alias prev=prevd
alias reddit="tuir --enable-media -s neovim"
alias rss=newsboat
alias revisit="~/Scripts/revisit.sh"
alias screensaver=Scripts/animation.sh
alias search=fd
alias searxng="/home/unknown/Apps/searxng/run.sh"
alias sndvol=pulsemixer
alias solitaire="~/Apps/tty-solitaire/ttysolitaire"
alias stumble="~/Scripts/stumble.sh"
alias subs="gaupol"
alias telegram=arigram
alias tetris="~/Apps/bastet/bastet"
alias torrent=transmission-cli
alias torrent-search="we-get --search"
alias vm="sudo virt-manager"
alias weather=Scripts/weather.sh
alias websearch="sr sx"
alias ws="sr sx"
alias wiki="phetch gopher://gopherpedia.com:70"
alias www="w3m http://searx:8080"
alias yt="ytfzf -st"
alias ytdl=yt-dlp
